# Generated by Django 4.1.7 on 2023-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeitnerBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("translate", models.CharField(max_length=50)),
                ("pronounce", models.CharField(blank=True, max_length=50, null=True)),
                ("counter", models.IntegerField(max_length=4)),
                ("example", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
